### ISSUE TITLE
example of view_records.py

### ISSUE THREAD

**Issue by GOBish** [EricThomson/tfrecord-view#1]
Hi,
Could you please give an example of how to launch view_records.py with the correct parameters (filename, dictionary of classes, etc).
I am having trouble getting it to work because I think I am not formatting the inputs correctly.

**Comment by GOBish** [comment]
nevermind, I figured it out in the main section.
Thank you for this utility.

**Comment by EricThomson** [comment]
Good let me know if anything is not clear. It is a bit rough around the edges not plug and play for sure.
